name: Build pages non trunk

on:
  push:
    branches:
      - "*"
      - "!main"

jobs:
  build:
    runs-on: ubuntu-latest
    container: node:17
    steps:
    - name: "Install deps"
      run: |
        apt update
        apt install python3 make g++ git openssl zip

    - name: Checkout Code
      uses: actions/checkout@v2

    - name: "yarn deps"
      run: |
        yarn

    - name: "yarn build"
      run: |
        yarn build

    - name: "yarn build"
      run: |
        zip -r build.zip ./build

    - uses: actions/upload-artifact@v2
      with:
        name: pages-rendering
        path: ./build.zip
