name: Deploy to pages on trunk

on:
  push:
    branches:
      - 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest
    container: node:16-alpine
    steps:
      - name: 'Install deps'
        run: |
          apk add python3 py3-pip make g++ git
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install J2
        run: |
          pip install j2cli
      - name: Set env
        run: |
          # Gets repository name (without owner prefix) variable
          echo "REPOSITORY_NAME=$(echo ${GITHUB_REPOSITORY} | cut -d "/" -f2)" >> $GITHUB_ENV
      - name: Generate docusaurus.config.js.j2
        run: |
          j2 docusaurus.config.js -o docusaurus.config.js
          cat docusaurus.config.js
      - name: 'yarn deps'
        run: |
          yarn
      - name: 'yarn deploy'
        run: |
          git config --global user.name 'ChiaAutomation'
          git config --global user.email 'automation@chia.net'
          GIT_USER=ChiaAutomation GIT_PASS=${{ github.token }} yarn deploy
